apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tf-vault-infra-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
      - name: upstream_repo
        value: quay.io/bradfordwagner/terraform
      - name: upstream_tag
        value: 1.0.0
    dag:
      tasks:
      - name: terraform
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/tf-vault-infra.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
        templateRef:
          name: flavor-terraform-template
          template: "{{inputs.parameters.git_ref_type}}"
        withItems:
        - { platform: alpine_3.14     , runtime_platforms: [linux/arm64] }

