apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tf-vault-infra-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
      value: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    dag:
      tasks:
      - name: terraform
        arguments:
          parameters:
          - name: git_ref_type
            value: "{{ inputs.parameters.git_ref_type }}"
          - name: git_repo
            value: https://github.com/bradfordwagner/tf-vault-infra.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: terraform_image
            value: quay.io/bradfordwagner/terraform:1.6.0-ubuntu_focal
          - name: vault_secrets_enabled
            value: false
          - name: vault_role
            value: ""
          - name: vault_issue_token
            value: false
          - name: csi_class
            value: sp-infra
          - name: csi_secret
            value: sp-infra
        templateRef:
          name: flavor-terraform-template
          template: main
